usr/include/wk2gtkpdf/*
usr/lib/*/libwk2gtkpdf-*.so
usr/lib/*/pkgconfig/*.pc

examples/01-minimal-cpp       usr/share/doc/libwk2gtkpdf-dev/examples/
examples/02-gtk3-integration  usr/share/doc/libwk2gtkpdf-dev/examples/
examples/03-gtk4-integration  usr/share/doc/libwk2gtkpdf-dev/examples/
examples/04-business-form     usr/share/doc/libwk2gtkpdf-dev/examples/
examples/05-pdf-anchor        usr/share/doc/libwk2gtkpdf-dev/examples/
examples/06-html-tests        usr/share/doc/libwk2gtkpdf-dev/examples/
